fix errors on ad-hoc retrieval pages
NTMC-Community/awaresome-neural-models-for-semantic-match pull request #43
Opened 2020-08-23 14:53 UTC by Albert-Ma

2020-08-23 14:53 UTC, Albert-Ma commented
@Chriskuei

2020-08-24 01:34 UTC, Chriskuei requested changes

2020-08-24 01:34 UTC, Chriskuei commented on Ad-hoc-Information-Retrieval/Ad-hoc-Information-Retrieval.md
>  |  ----  | ----  |----  | ----  | ----  | ----  |
Delete `Gov2 todo`

2020-08-24 01:34 UTC, Chriskuei commented on Ad-hoc-Information-Retrieval/Ad-hoc-Information-Retrieval.md
> +### MS MARCO
Delete `MS MARCO`

2020-08-24 02:14 UTC, merged