Pi fix
NTMC-Community/awaresome-neural-models-for-semantic-match pull request #44
Opened 2020-08-23 23:53 UTC by dyuyang

2020-08-24 01:43 UTC, Chriskuei requested changes

2020-08-24 01:43 UTC, Chriskuei commented on Paraphrase-Identification/Paraphrase-Identification.md
> +| XLNet-Large (ensemble) (Yang et al., 2019) |  [official](https://github.com/zihangdai/xlnet/) | 93.0  | 90.7 | [XLNet: Generalized Autoregressive Pretraining for Language Understanding](https://arx
Use badge [![official](https://img.shields.io/badge/official-code-brightgreen)](https://github.com/faneshion/DRMM) or [![MatchZoo](https://img.shields.io/badge/matchzoo-ready-green)](https://github.com/NTMC-Community/MatchZoo/blob/master/matchzoo/models/drmm.py)

2020-08-25 00:56 UTC, dyuyang commented on Paraphrase-Identification/Paraphrase-Identification.md
> +| XLNet-Large (ensemble) (Yang et al., 2019) |  [official](https://github.com/zihangdai/xlnet/) | 93.0  | 90.7 | [XLNet: Generalized Autoregressive Pretraining for Language Understanding](https://arx
Badges had been added

2020-08-25 07:04 UTC, Chriskuei approved these changes

2020-08-25 07:04 UTC, merged