update new models and datasets recently published
NTMC-Community/awaresome-neural-models-for-semantic-match pull request #50
Opened 2020-11-14 08:36 UTC by wuchen95

update new models and datasets recently published
#49

2020-11-14 12:35 UTC, bwanglzu commented
@wuchen95 thanks! @faneshion can you review?

2020-12-04 11:20 UTC, Chriskuei requested changes

2020-12-04 11:20 UTC, Chriskuei commented on Response-Retrieval/Response-Retrieval.md
> +Revised Person
Add a blank line

2020-12-06 10:45 UTC, Chriskuei approved these changes

2020-12-06 10:46 UTC, merged